### ISSUE TITLE
Docker image? Requesting access to the LIDAR-RGBD dataset

### ISSUE THREAD

**Issue by Mechazo11** [XuRobotics/slide-slam#5]
Hello @XuRobotics 
Thank you very much for making this fantastic paper publicly available.

I am interested in trying out the system. Will the group be releasing a Docker image?

Also can would it be possible get access to the LIDAR-RGBD dataset with its CAD model and ground truth poses? I am primarily interested in Experiment 2 that contained 4 robots, RGBD data and indoor scenario.

With best regards,
@Mechao11

**Comment by XuRobotics** [comment]
Hi @Mechazo11,

Thank you for your kind words! Please see my response below. 

_I am interested in trying out the system. Will the group be releasing a Docker image?_
We are currently working on additional exciting functionalities and refactoring our code stack to make it easy to build and use. We plan to start releasing our core code base by the end of September. As for docker, sure, we will try to include a docker image in our release as well. 

_Also can would it be possible get access to the LIDAR-RGBD dataset with its CAD model and ground truth poses? I am primarily interested in Experiment 2 that contained 4 robots, RGBD data and indoor scenario._
-- Although we have not planned to do this yet, I don’t anticipate any issues with making it available. We’ll consider this request and keep you posted!

Best,
Xu

**Comment by Mechazo11** [comment]
Hi @XuRobotics 
Thank you very much for your response. I will keep an eye out for the link to the dataset. 

With best,
@Mechazo11

**Comment by DanielChaseButterfield** [comment]
@XuRobotics Thanks again for releasing this repository, the organizational structure and code makes it clear that your refactoring efforts weren't wasted.

I'd like to inquire if you had come to a decision on releasing Experiment 2. Were you able to decide if you're planning on making it available, and if so, would you include GT poses and CAD model? 

We'd find it incredibly useful to have access to this data with the GT poses so that we can build on this repository and quickly evaluate.
